import { HummerH1Model } from "./HummerH1Model";
import { HummerH2Model } from "./HummerH2Model";

const hummerH1 = new HummerH1Model();
hummerH1.run();

console.log('===================');
// 悍马H2 默认行为
const hummerH2 = new HummerH2Model();
hummerH2.run();

console.log('===================');
// H2 关闭鸣笛
hummerH2.setAlarm(false);
hummerH2.run();

/**
 * Output:
 
悍马H1 启动...
悍马H1 引擎声响...
悍马H1 鸣笛...
悍马H1 停车...
===================
悍马H2 启动...
悍马H2 引擎声响...
悍马H2 鸣笛...
悍马H2 停车...
===================
悍马H2 启动...
悍马H2 引擎声响...
悍马H2 停车...

 */